sudo: false
language: scala
sbt_args:
  # this tells SBT to use whatever Scala version Travis has selected
  - ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M
  # we can only build against the Oracle JDK, because we need the latest Nashorn
  jdk: oraclejdk8
  # Use JDK 8u45+ explicitly
  addons:
    apt:
      packages:
        - oracle-java8-installer
scala:
  ### Build against the following Scala versions: #############################
  - 2.12.0-M5 # latest milestone release of upcoming Scala major version
  - 2.11.8    # current Scala version
  - 2.10.6    # latest maintainance release of previous Scala major version
env:
  global:
    - TERM=dumb # this tells ScalaTest not to use certain ANSI escapes
    ### API keys for various services: ########################################
    - secure: "YuNk044kHaTT23R5ZNZxyWvS0jLBorcANahDPVw3FTd4CjcBAqm70xDCjSahTwywxoCSkF1mCQszNSqeGTAvsAHqn4CVpUxQBG7IdSRlWJx9Y2HECoPpNNIvBOSrqXlToEDFeHJdSasaLSVoTqz1CzYmXeU4glgFGqIkODbCqWifD0TKHZyiEQ9IlXiVyv52Geb4JTX0RNoTYWnQQh2INPiUSRz9SxRS6tzkfXLHTDM8MIaBVinno0wfkwEsNPPH3Wv1RelzuC2IkmWcba+Ntc51NtB/34TsaYMEFx9pTVwjQ8JSAioUkuHTmRnHy3V9C5ZlqhmVzDCGxqX3p1gc/9fMKHu3RlAAeQo+vKa18Kfcs8ugVtWLcRLKy8uAGvxGPWFbv9PPm1QUnW+uhPwI32DW1ZoeStRxzCUm4TKg/yHHPxQDqNuyhy9Lc7j/61DJqwAVb8cj70dzSi1RUJXlOmGKHci5E+7iKi4Tsghyx7nOVzJdLfwn2xXICl/PixMW+aMAWjbMSUnBOpdgGRYYT6AXQsVaDatHnk+WS78XEaAnXsk/AvGOpc8DB4uEbEx7uhZnK5kG0jYmO/y+fhvyXMfZlodgbbgZl9Yy2Y2XsRep7RVj7mXkcIkX0WJa/Q/bvSrQ2UJKxsA844zJylQytT1Tn6UwO9uknsR/bW9hcYM="
    - secure: "y7H6ah4bMFpdl9nviqKHwTptLRABri2CM/5dwRR0jH2BMdeYt3tDwyX7jPH1GGdvG9+YQapBfP+Gnt629hAmmXS4Naz8+5wndS4/G2hpcdnzpE/zjm5yEXKgPIe1gNkmMPmu5RqRdG5StJNWYfeZQTazmN8g15HIdGN7sMIJ9BfQW20wgxkG1iEXnLlQNadJfMhoismEwvHKOXICGG7xBPD7dMrZZCKsFZqY06/y+aLZGPvHKSTm6qYExNMG+xsBNgluLi1hp4JQwye/qIh4ohMkjumVcYPmzzHfd3Nw4Qt/aytTP75L5w9tVVx+XLyM0+/51nc6dSWyhx1lk+yyWMloUqtTJNSB4vlST9QLPVzfiwSajzLbMAzGSFz0wQSGg0AbgCfUhgDeSQG4y24Tw1A3B9gyCHcbQAelI7lqq+yQli6NS+KYNl8hKTyeGTkONEck9npFxVlxHydNawYHvmWqo3JYtfJIhpBoq6gMCEfwaFTAYrRo6Ps7FXckGvo69eOHgOYh28k3k5OIdlqMdt3S0h6BZ8HwF3xRkiKU5DBmqdYoEPcNkY5c5W3lZjYX/6Z2yNp40DhKnzNjqzOqPjgWS6E54AMf8lGuFZ00WN2QWfVWNz+SuZw58tZuhUnlZCOA5+041GkMQUyEebj82Mym3H2y6sNjQ3lvNRyjfLg="

matrix:
  fast_finish: true
  allow_failures:
    ### Builds against non-current Scala versions are allowed to fail #########
    - scala: 2.12.0-M5
    - scala: 2.10.6
# we can only build against the Oracle JDK, because we need the latest Nashorn
jdk: oraclejdk8
# Use JDK 8u45+ explicitly
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    # save the Ivy cache so we don't need to re-download dependencies as often
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  ### Script to build Ionesco #################################################
  - sbt all/compile                     # compile
  - sbt clean coverage
  - sbt all/test # run tests
    # remove SBT lockfile and Ivy properties so they don't get cached
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  ### Report test coverage ####################################################
  - sbt all/coverageReport     # generate Cobertura coverage report
  - sbt all/coverageAggregate  # aggregate coverage reports from subprojects
  - sbt all/codacyCoverage     # report coverage to Codacy
  - bash <(curl -s https://codecov.io/bash) # upload coverage to Codecov.io
  ### Check dependencies and licenses on VersionEye ###########################
  - sbt all/versioneye:updateProject
  - sbt all/versioneye:licenseCheck
